In [30]:
# from torch.utils.data import DataLoader
import numpy as np
# import sys


# sys.path.append("../")
# from locationing_dataset import MyLocationingDataSet as LocDataset
# from train1 import plot_inference_loc

In [2]:
# ### Get Data Sample[1] and Fictitious Prediction

# root_dir = "C:/Users/KZTYLF/Documents/playground/GNN UIs/GNN InstanceSegmentation/Recreating Dataset/locationing_dataset/test/"
# pc_dir = root_dir+"point_clouds/"
# gt_dir = root_dir+"labels/"
# sample_index = 0
# graph, label = LocDataset(pc_dir, gt_dir)[sample_index]

# prediction = np.array([[0.25, 0.75]])

In [3]:
# ## Plotting

# plot_inference_loc(prediction, graph, False, additional_pts=True)

In [4]:
# for i in range(5):
#     print(i)
#     if i == 3:
#         break

In [7]:
import torch
from torch import nn, sigmoid
from torch.nn import MSELoss
# from torch.nn.functional import sigmoid

In [26]:
a = torch.Tensor([[1, 2, 3], [2, 3,4], [4, 4,5]])
b = a +5
a = sigmoid(a)

In [27]:
amax = torch.amax(a, dim=0)
bmax = torch.amax(b, dim=0)
print(amax)
print(bmax)

tensor([0.9820, 0.9820, 0.9933])
tensor([ 9.,  9., 10.])


In [28]:
mse = MSELoss()
(mse(amax, bmax))


tensor(69.8989)

In [51]:
arr1 = np.arange(10).reshape((5,2))
arr2 = np.arange(10,20).reshape((5,2))
list_arrs = [arr1, arr2]
print(list_arrs)

[array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]]), array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])]


In [52]:
for i in list_arrs:
    i += 5
print(list_arrs)

[array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]]), array([[15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])]


In [44]:
# output = torch.Tensor([[1, 2, 3], [1, 2, 3]])
output = torch.Tensor([[1, 2, 3]])
# target = torch.Tensor([[1, 2, 2], [1, 2, 2]])
target = torch.Tensor([[1, 2, 2]])
print(output)

tensor([[1., 2., 3.]])


In [45]:
(output-target)**2

tensor([[0., 0., 1.]])

In [48]:
torch.sum((output-target)**2)**(1/2)

tensor(1.)

In [49]:
torch.inf

inf

In [50]:
5>torch.inf

False

In [56]:
file_path = "C:/Users/KZTYLF/Documents/playground/GNN UIs/GNN InstanceSegmentation/Recreating Dataset/locationing_dataset/train/point_clouds/WELD_LH-1--2312012-NoResult-s-2023_06_02-12-50-30-1_1.npy"
mat1 = np.load(file_path)

In [57]:
mat1.shape

(421, 2)

In [59]:
mat1 = np.hstack((mat1, np.zeros((mat1.shape[0], 1))))
mat1

array([[-77.70000458,   0.19999962,   0.        ],
       [-77.70000458,   7.54999971,   0.        ],
       [-79.55000687,  19.15000057,   0.        ],
       ...,
       [-78.00000763,  18.39999962,   0.        ],
       [-79.70000458,  18.55000019,   0.        ],
       [-79.17500496,  19.2249999 ,   0.        ]])