In [1]:
import numpy as np
import os
from LocReg_model import LocationRegressionModelV1
from locationing_dataset import MyLocationingDataSet as LocDataset
import torch
from torch.utils.data import DataLoader

In [2]:
########
## [1]
########
## First Q to run Predictions on AlL samples withing a spec'd directory
## Using a choice of saved Model Parameters

In [17]:
######## Settings

### Checking the test set
# weld_pc_dir = "./Recreating Dataset/locationing_dataset/test/point_clouds/"
# labels_dir = "./Recreating Dataset/locationing_dataset/test/labels/"

### Checking the train set
weld_pc_dir = "./Recreating Dataset/locationing_dataset/train/point_clouds/"
labels_dir = "./Recreating Dataset/locationing_dataset/train/labels/"

assert os.path.isdir(weld_pc_dir), "PC directory location does not exist"
assert os.path.isdir(labels_dir), "Labels directory location does not exist"

## Model Parameters
root = "./_loc_model/original_test/"
# model_params_path = root+'2024_01_06_16_00_26/min_test_loss_params_epoch_2.pt'
model_params_path = root+'2024_01_06_16_00_26/params_epoch_0_2024_01_06_16_01_53.pt'
# model_params_path = root+'2024_01_06_16_00_26/params_epoch_1_2024_01_06_16_03_19.pt'
# model_params_path = root+'2024_01_06_16_00_26/min_test_loss_params_epoch_2.pt'
# model_params_path = root+'2024_01_06_16_00_26/min_test_loss_params_epoch_2.pt'

assert os.path.isfile(model_params_path)

## Model Defined:
model = LocationRegressionModelV1()
device = "cpu"


######## Setup
## The Model
model.load_state_dict(torch.load(model_params_path))
model.to(device)
model.eval()

## The Data
dataset = LocDataset(weld_pc_dir, labels_dir)
dataloader = DataLoader(dataset, batch_size=1)
print(f"To process {len(dataloader)} point clouds from {weld_pc_dir}")

with torch.no_grad():
    for i, (X, y) in enumerate(dataloader):
        y = y.to(device)
        y = torch.squeeze(y, 0)

        keys = ("vertex_coord_list", "keypoint_indices_list", "edges_list")
        for key in keys:
            X[key] = [torch.squeeze(tensor,0).to(device) for tensor in X[key]]

        pred = model(X)
        print(pred)

To process 1908 point clouds from ./Recreating Dataset/locationing_dataset/train/point_clouds/
tensor([[0.0000, 0.0000, 1.0696]])
tensor([[0.0000, 0.3601, 3.5407]])
tensor([[0.0000, 0.0000, 1.4660]])
tensor([[0.0000, 0.0000, 6.2845]])
tensor([[0.0000, 0.0000, 2.4363]])
tensor([[0.0000, 0.0000, 1.8415]])
tensor([[0.0000, 0.0000, 1.7142]])
tensor([[0.0000, 0.0515, 1.3609]])
tensor([[0.0000, 0.0674, 1.3757]])
tensor([[0.0000, 0.0000, 6.0615]])
tensor([[0.0000, 0.0000, 3.1352]])
tensor([[0.0000, 0.0832, 1.2051]])
tensor([[0.0000, 0.0000, 1.2617]])
tensor([[0.0000, 0.0000, 1.5566]])
tensor([[0.0000, 0.0000, 1.7015]])
tensor([[ 0.0000,  0.0000, 39.6327]])
tensor([[0.0000, 0.0000, 2.6291]])
tensor([[0.0000, 0.0000, 1.4407]])
tensor([[0.0000, 0.0000, 2.6318]])
tensor([[ 0.0000,  0.0000, 13.1201]])
tensor([[0.0000, 0.0000, 1.3753]])
tensor([[0.0000, 0.1842, 1.6663]])
tensor([[0.0000, 0.0000, 1.6255]])
tensor([[0.0000, 0.0443, 1.2284]])
tensor([[0.0000, 0.0000, 1.3299]])
tensor([[0.0000, 0.0000,

tensor([[0.0000, 0.0000, 4.8610]])
tensor([[0.0000, 0.7616, 9.3711]])
tensor([[0.0000, 0.0000, 1.5820]])
tensor([[0.0000, 0.0000, 1.5261]])
tensor([[0.0000, 0.0000, 1.1520]])
tensor([[0.0000, 0.0850, 1.2461]])
tensor([[0.0000, 0.0000, 1.5624]])
tensor([[0.0000, 0.0000, 1.6393]])
tensor([[0.0000, 0.0907, 1.5783]])
tensor([[0.0000, 0.0000, 1.1084]])
tensor([[0.0000, 0.0000, 2.3660]])
tensor([[0.0000, 0.0000, 1.3711]])
tensor([[0.0000, 0.0000, 4.6993]])
tensor([[0.0000, 0.0000, 1.1928]])
tensor([[0.0000, 0.0000, 2.0028]])
tensor([[0.0000, 0.0000, 1.3926]])
tensor([[0.0000, 0.2226, 2.7879]])
tensor([[0.0000, 0.0815, 1.3490]])
tensor([[0.0000, 0.0000, 1.8399]])
tensor([[0.0000, 0.0000, 6.2219]])
tensor([[0.0000, 0.0000, 2.0117]])
tensor([[0.0000, 0.0582, 1.2139]])
tensor([[ 0.0000,  0.0000, 10.1159]])
tensor([[0.0000, 0.0564, 1.5451]])
tensor([[0.0000, 0.0000, 2.3868]])
tensor([[0.0000, 0.0000, 1.1998]])
tensor([[0.0000, 0.0000, 1.6114]])
tensor([[0.0000, 0.0000, 8.6833]])
tensor([[ 0.0000,

tensor([[0.0000, 0.0000, 1.5602]])
tensor([[0.0000, 0.1358, 1.4969]])
tensor([[0.0000, 0.0000, 9.4106]])
tensor([[0.0000, 0.0000, 2.2879]])
tensor([[0.0000, 0.0000, 1.5480]])
tensor([[0.0000, 0.0000, 1.3295]])
tensor([[0.0000, 0.0970, 1.3291]])
tensor([[0.0000, 0.0000, 1.1019]])
tensor([[0.0000, 0.0000, 1.3581]])
tensor([[0.0000, 0.0000, 1.3469]])
tensor([[0.0000, 0.0000, 1.4706]])
tensor([[0.0000, 0.0000, 1.6659]])
tensor([[0.0000, 0.0000, 1.7466]])
tensor([[0.0000, 0.0000, 1.8573]])
tensor([[0.0000, 0.0000, 1.6418]])
tensor([[0.0000, 0.0000, 1.5379]])
tensor([[0.0000, 0.0000, 1.3820]])
tensor([[0.0000, 0.0000, 1.5590]])
tensor([[0.0000, 0.0000, 5.4800]])
tensor([[0.0000, 0.0000, 1.4355]])
tensor([[0.0000, 0.2146, 1.6520]])
tensor([[0.0000, 0.0000, 1.8075]])
tensor([[0.0000, 0.0000, 1.6868]])
tensor([[0.0000, 0.0000, 1.5326]])
tensor([[0.0000, 0.0185, 1.4755]])
tensor([[0.0000, 0.0000, 1.6154]])
tensor([[ 0.0000,  0.0000, 13.7774]])
tensor([[0.0000, 0.0309, 1.2524]])
tensor([[0.0000, 

tensor([[0.0000, 0.0000, 2.3639]])
tensor([[0.0000, 0.0000, 4.2329]])
tensor([[0.0000, 0.0000, 1.3872]])
tensor([[0.0000, 0.0067, 1.5403]])
tensor([[0.0000, 0.4287, 3.1443]])
tensor([[0.0000, 0.0000, 5.5261]])
tensor([[0.0000, 0.0000, 4.5333]])
tensor([[ 0.0000,  0.0000, 10.7375]])
tensor([[0.0000, 0.3112, 1.8508]])
tensor([[0.0000, 0.0000, 2.5262]])
tensor([[0.0000, 0.0000, 2.1486]])
tensor([[ 0.0000,  0.0000, 11.4045]])
tensor([[0.0000, 0.0000, 1.0291]])
tensor([[0.0000, 0.0000, 3.9301]])
tensor([[0.0000, 0.0673, 1.5051]])
tensor([[0.0000, 0.4034, 3.2459]])
tensor([[0.0000, 0.0000, 6.2510]])
tensor([[0.0000, 0.0000, 1.5876]])
tensor([[0.0000, 0.0000, 1.7316]])
tensor([[0.0000, 0.0000, 1.4106]])
tensor([[0.0000, 0.0000, 2.1985]])
tensor([[0.0000, 0.0000, 4.1116]])
tensor([[0.0000, 0.0000, 6.1688]])
tensor([[0.0000, 0.0000, 1.6236]])
tensor([[0.0000, 0.0171, 1.7165]])
tensor([[0.0000, 0.0000, 1.3237]])
tensor([[0.0000, 0.0000, 1.3358]])
tensor([[0.0000, 0.0000, 5.8766]])
tensor([[0.000

tensor([[0.0000, 0.0000, 2.5210]])
tensor([[0.0000, 0.0000, 5.9473]])
tensor([[0.0000, 0.2039, 1.7198]])
tensor([[0.0000, 0.0000, 2.6480]])
tensor([[0.0000, 0.0000, 1.1959]])
tensor([[0.0000, 0.0000, 1.0858]])
tensor([[0.0000, 0.0000, 1.4571]])
tensor([[0.0000, 0.0000, 3.0828]])
tensor([[0.0000, 0.0000, 1.5488]])
tensor([[ 0.0000,  0.0000, 38.9256]])
tensor([[0.0000, 0.0000, 1.6900]])
tensor([[0.0000, 0.0000, 2.3818]])
tensor([[0.0000, 0.0000, 1.2663]])
tensor([[0.0000, 0.0000, 1.6924]])
tensor([[0.0000, 0.0853, 1.3407]])
tensor([[0.0000, 0.0000, 1.3723]])
tensor([[ 0.0000,  0.0000, 15.5829]])
tensor([[0.0000, 0.0000, 2.0972]])
tensor([[0.0000, 0.0000, 1.2312]])
tensor([[0.0000, 0.0000, 4.6481]])
tensor([[0.0000, 0.0000, 1.2792]])
tensor([[0.0000, 0.0000, 1.8302]])
tensor([[0.0000, 0.0000, 1.3604]])
tensor([[0.0000, 0.0000, 1.3266]])
tensor([[ 0.0000,  0.0000, 14.9930]])
tensor([[0.0000, 0.0000, 6.5701]])
tensor([[0.0000, 0.0000, 1.7769]])
tensor([[0.0000, 0.0000, 1.1160]])
tensor([[0.

tensor([[0.0000, 0.0000, 1.4753]])
tensor([[0.0000, 0.0000, 1.5564]])
tensor([[0.0000, 0.0000, 1.1424]])
tensor([[0.0000, 0.0000, 2.4686]])
tensor([[0.0000, 0.5512, 1.4781]])
tensor([[0.0000, 0.0287, 1.4633]])
tensor([[0.0000, 0.0000, 1.2599]])
tensor([[0.0000, 0.0000, 1.9244]])
tensor([[0.0000, 0.0000, 1.3193]])
tensor([[0.0000, 0.0000, 2.6702]])
tensor([[0.0000, 0.0000, 1.3340]])
tensor([[0.0000, 0.0000, 4.1119]])
tensor([[0.0000, 0.0000, 1.4783]])
tensor([[0.0000, 0.0000, 2.6146]])
tensor([[0.0000, 0.0000, 1.3227]])
tensor([[0.0000, 0.0000, 1.5720]])
tensor([[ 0.0000,  0.0000, 15.0009]])
tensor([[0.0000, 0.0000, 2.3710]])
tensor([[0.0000, 0.0000, 1.4055]])
tensor([[0.0000, 0.0000, 2.7216]])
tensor([[0.0000, 0.1708, 1.1410]])
tensor([[0.0000, 2.5783, 8.8249]])
tensor([[0.0000, 0.0000, 1.3423]])
tensor([[0.0000, 0.0548, 3.2753]])
tensor([[0.0000, 0.0000, 1.6251]])
tensor([[0.0000, 0.0000, 2.0769]])
tensor([[0.0000, 0.0000, 3.8450]])
tensor([[0.0000, 0.0000, 1.2976]])
tensor([[0.0000, 

tensor([[0.0000, 0.0000, 1.3681]])
tensor([[0.0000, 0.2657, 1.3795]])
tensor([[0.0000, 0.0000, 1.5798]])
tensor([[0.0000, 0.0000, 1.4284]])
tensor([[0.0000, 0.0000, 1.5880]])
tensor([[0.0000, 0.0000, 1.4049]])
tensor([[0.0000, 0.0000, 1.2087]])
tensor([[0.0000, 0.0000, 2.0492]])
tensor([[ 0.0000,  0.0000, 17.1438]])
tensor([[0.0000, 0.0000, 1.2180]])
tensor([[0.0000, 0.0000, 2.0153]])
tensor([[0.0000, 0.0000, 1.5837]])
tensor([[0.0000, 0.0000, 1.3713]])
tensor([[0.0000, 0.0000, 2.8334]])
tensor([[0.0000, 0.0000, 1.9750]])
tensor([[0.0000, 0.0000, 1.2310]])
tensor([[0.0000, 0.0000, 2.0380]])
tensor([[0.0000, 0.0000, 4.2701]])
tensor([[0.0000, 0.0000, 4.3027]])
tensor([[0.0000, 0.0000, 1.2801]])
tensor([[0.0000, 0.0000, 1.5182]])
tensor([[0.0000, 0.0000, 1.6092]])
tensor([[0.0000, 0.0000, 1.8511]])
tensor([[0.0000, 0.0000, 5.5834]])
tensor([[0.0000, 0.0000, 1.3219]])
tensor([[0.0000, 0.0000, 1.4386]])
tensor([[0.0000, 0.0000, 6.0439]])
tensor([[0.0000, 0.0000, 2.5902]])
tensor([[0.0000, 

tensor([[ 0.0000,  0.0000, 36.1791]])
tensor([[0.0000, 0.0000, 1.6288]])
tensor([[ 0.0000,  0.0000, 15.5018]])
tensor([[0.0000, 0.0000, 4.3106]])
tensor([[0.0000, 0.0000, 1.3788]])
tensor([[0.0000, 0.3306, 1.6865]])
tensor([[0.0000, 0.0000, 5.8946]])
tensor([[ 0.0000,  0.0000, 18.7584]])
tensor([[ 0.0000,  7.1839, 72.2040]])
tensor([[0.0000, 0.0000, 1.6633]])
tensor([[0.0000, 0.0000, 5.3644]])
tensor([[0.0000, 0.0070, 1.1294]])
tensor([[0.0000, 0.0000, 2.5397]])
tensor([[0.0000, 0.0550, 1.2557]])
tensor([[0.0000, 0.0000, 2.5708]])
tensor([[0.0000, 0.0000, 2.8343]])
tensor([[0.0000, 0.0000, 1.3182]])
tensor([[0.0000, 0.0000, 2.1328]])
tensor([[0.0000, 0.0000, 1.5883]])
tensor([[0.0000, 0.0000, 1.6824]])
tensor([[ 0.0000,  0.0000, 37.9618]])
tensor([[0.0000, 0.0000, 2.3627]])
tensor([[0.0000, 0.0000, 1.3964]])
tensor([[0.0000, 0.0000, 1.6780]])
tensor([[0.0000, 0.0000, 4.3802]])
tensor([[0.0000, 0.1151, 2.1595]])
tensor([[0.0000, 0.0000, 1.3598]])
tensor([[0.0000, 0.1166, 1.9979]])
tenso

tensor([[0.0000, 0.0000, 4.6115]])
tensor([[0.0000, 0.0033, 1.3345]])
tensor([[0.0000, 0.0372, 1.7745]])
tensor([[0.0000, 0.0000, 1.9654]])
tensor([[0.0000, 0.0000, 1.7888]])
tensor([[0.0000, 0.0000, 3.0248]])


OrderedDict([('multi_point_pooling.point_linears.0.weight',
              tensor([[ 0.3645, -0.2389,  0.3196],
                      [-0.1652,  0.2026,  0.1020],
                      [-0.2640,  0.0196,  0.2058],
                      [ 0.2733, -0.3418, -0.3930],
                      [ 0.2089, -0.3453,  0.0435],
                      [-0.3880,  0.2832,  0.3473],
                      [-0.0845,  0.3676, -0.0583],
                      [-0.4616, -0.2992,  0.3410],
                      [ 0.2743,  0.1224, -0.2740],
                      [ 0.3531, -0.1998, -0.1684],
                      [ 0.4452, -0.3900, -0.1517],
                      [ 0.0652,  0.4550,  0.2326],
                      [-0.1946, -0.1470, -0.0767],
                      [ 0.4262,  0.0674,  0.4400],
                      [ 0.4041,  0.0467,  0.3474],
                      [ 0.3677,  0.0313,  0.1029],
                      [ 0.2875, -0.4296,  0.4313],
                      [ 0.4291,  0.2419,  0.2971],
                      

In [19]:
a = 5
if a % 5 == 0 or a == 5:
    print("true")

true
