In [1]:
import numpy as np

In [15]:
np.random.seed(0)
arr = np.random.random((5, 3))
xmin, ymin  = np.amin(arr[:, :2], 0)
# xmin, ymin, _ = arr_min
print(arr)
print()
print(xmin)
print(ymin)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]

0.3834415188257777
0.4236547993389047


In [23]:
pc = np.random.randint(10, size=(10, 3))
# pc = np.array([3,4,5]).reshape((1,3))
print("pc")
print(pc)
print()

xmin, ymin = np.amin(pc[:, :2],0)
pc_min = np.amin(pc[:, :2],0)
print("pc_min")
print(pc_min)
print()

xmax, ymax = np.amax(pc[:, :2],0)
pc_max = np.amax(pc[:, :2],0)
print("pc_max")
print(pc_max)
print()

pc_span = pc_max - pc_min
pc  = (pc[:, :2] - pc_min)/pc_span

print(pc)

pc
[[8 1 1]
 [0 3 8]
 [8 4 4]
 [0 9 3]
 [7 3 2]
 [1 1 2]
 [1 4 2]
 [5 5 5]
 [2 5 7]
 [7 6 1]]

pc_min
[0 1]

pc_max
[8 9]

[[1.    0.   ]
 [0.    0.25 ]
 [1.    0.375]
 [0.    1.   ]
 [0.875 0.25 ]
 [0.125 0.   ]
 [0.125 0.375]
 [0.625 0.5  ]
 [0.25  0.5  ]
 [0.875 0.625]]


In [25]:
0.8/np.max(pc_span)

0.1